// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1:string):Promise<string>;

export function StartRealtimeScan():Promise<void>;

export function StartRootkitScan():Promise<void>;

export function StartScan():Promise<void>;
