// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function StartRealtimeScan() {
  return window['go']['main']['App']['StartRealtimeScan']();
}

export function StartRootkitScan() {
  return window['go']['main']['App']['StartRootkitScan']();
}

export function StartScan() {
  return window['go']['main']['App']['StartScan']();
}
