// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package agent

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type edrEvent struct {
	_    structs.HostLayout
	Pid  uint32
	Ppid uint32
	Comm [16]int8
}

type edrExitEvent struct {
	_   structs.HostLayout
	Pid uint32
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	edrMapExitRb             = "exit_rb"
	edrMapRb                 = "rb"
	edrProgHandleExecveExit  = "handle_execve_exit"
	edrProgHandleProcessExit = "handle_process_exit"
	edrVarUnusedEvent        = "unused_event"
	edrVarUnusedExitEvent    = "unused_exit_event"
)

// loadEdr returns the embedded CollectionSpec for edr.
func loadEdr() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_EdrBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load edr: %w", err)
	}

	return spec, err
}

// loadEdrObjects loads edr and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*edrObjects
//	*edrPrograms
//	*edrMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadEdrObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadEdr()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// edrSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type edrSpecs struct {
	edrProgramSpecs
	edrMapSpecs
	edrVariableSpecs
}

// edrProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type edrProgramSpecs struct {
	HandleExecveExit  *ebpf.ProgramSpec `ebpf:"handle_execve_exit"`
	HandleProcessExit *ebpf.ProgramSpec `ebpf:"handle_process_exit"`
}

// edrMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type edrMapSpecs struct {
	ExitRb *ebpf.MapSpec `ebpf:"exit_rb"`
	Rb     *ebpf.MapSpec `ebpf:"rb"`
}

// edrVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type edrVariableSpecs struct {
	UnusedEvent     *ebpf.VariableSpec `ebpf:"unused_event"`
	UnusedExitEvent *ebpf.VariableSpec `ebpf:"unused_exit_event"`
}

// edrObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadEdrObjects or ebpf.CollectionSpec.LoadAndAssign.
type edrObjects struct {
	edrPrograms
	edrMaps
	edrVariables
}

func (o *edrObjects) Close() error {
	return _EdrClose(
		&o.edrPrograms,
		&o.edrMaps,
	)
}

// edrMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadEdrObjects or ebpf.CollectionSpec.LoadAndAssign.
type edrMaps struct {
	ExitRb *ebpf.Map `ebpf:"exit_rb"`
	Rb     *ebpf.Map `ebpf:"rb"`
}

func (m *edrMaps) Close() error {
	return _EdrClose(
		m.ExitRb,
		m.Rb,
	)
}

// edrVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadEdrObjects or ebpf.CollectionSpec.LoadAndAssign.
type edrVariables struct {
	UnusedEvent     *ebpf.Variable `ebpf:"unused_event"`
	UnusedExitEvent *ebpf.Variable `ebpf:"unused_exit_event"`
}

// edrPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadEdrObjects or ebpf.CollectionSpec.LoadAndAssign.
type edrPrograms struct {
	HandleExecveExit  *ebpf.Program `ebpf:"handle_execve_exit"`
	HandleProcessExit *ebpf.Program `ebpf:"handle_process_exit"`
}

func (p *edrPrograms) Close() error {
	return _EdrClose(
		p.HandleExecveExit,
		p.HandleProcessExit,
	)
}

func _EdrClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed edr_bpfel.o
var _EdrBytes []byte
