// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package agent

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type filerFilerEvent struct {
	_        structs.HostLayout
	Pid      uint32
	Comm     [16]int8
	Filename [256]int8
	Flags    uint32
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	filerMapRb               = "rb"
	filerProgHandleOpenat    = "handle_openat"
	filerVarUnusedFilerEvent = "unused_filer_event"
)

// loadFiler returns the embedded CollectionSpec for filer.
func loadFiler() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_FilerBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load filer: %w", err)
	}

	return spec, err
}

// loadFilerObjects loads filer and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*filerObjects
//	*filerPrograms
//	*filerMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadFilerObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadFiler()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// filerSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type filerSpecs struct {
	filerProgramSpecs
	filerMapSpecs
	filerVariableSpecs
}

// filerProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type filerProgramSpecs struct {
	HandleOpenat *ebpf.ProgramSpec `ebpf:"handle_openat"`
}

// filerMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type filerMapSpecs struct {
	Rb *ebpf.MapSpec `ebpf:"rb"`
}

// filerVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type filerVariableSpecs struct {
	UnusedFilerEvent *ebpf.VariableSpec `ebpf:"unused_filer_event"`
}

// filerObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadFilerObjects or ebpf.CollectionSpec.LoadAndAssign.
type filerObjects struct {
	filerPrograms
	filerMaps
	filerVariables
}

func (o *filerObjects) Close() error {
	return _FilerClose(
		&o.filerPrograms,
		&o.filerMaps,
	)
}

// filerMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadFilerObjects or ebpf.CollectionSpec.LoadAndAssign.
type filerMaps struct {
	Rb *ebpf.Map `ebpf:"rb"`
}

func (m *filerMaps) Close() error {
	return _FilerClose(
		m.Rb,
	)
}

// filerVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadFilerObjects or ebpf.CollectionSpec.LoadAndAssign.
type filerVariables struct {
	UnusedFilerEvent *ebpf.Variable `ebpf:"unused_filer_event"`
}

// filerPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadFilerObjects or ebpf.CollectionSpec.LoadAndAssign.
type filerPrograms struct {
	HandleOpenat *ebpf.Program `ebpf:"handle_openat"`
}

func (p *filerPrograms) Close() error {
	return _FilerClose(
		p.HandleOpenat,
	)
}

func _FilerClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed filer_bpfeb.o
var _FilerBytes []byte
