// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package agent

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type networkNetworkEvent struct {
	_        structs.HostLayout
	Pid      uint32
	Comm     [16]int8
	Family   uint16
	Port     uint16
	Ip4      uint32
	Ip6      [16]uint8
	Protocol uint8
	_        [3]byte
	Len      uint32
	Data     [256]int8
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	networkMapRb                 = "rb"
	networkProgHandleConnect     = "handle_connect"
	networkProgHandleSendto      = "handle_sendto"
	networkProgHandleSocket      = "handle_socket"
	networkVarUnusedNetworkEvent = "unused_network_event"
)

// loadNetwork returns the embedded CollectionSpec for network.
func loadNetwork() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_NetworkBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load network: %w", err)
	}

	return spec, err
}

// loadNetworkObjects loads network and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*networkObjects
//	*networkPrograms
//	*networkMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadNetworkObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadNetwork()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// networkSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type networkSpecs struct {
	networkProgramSpecs
	networkMapSpecs
	networkVariableSpecs
}

// networkProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type networkProgramSpecs struct {
	HandleConnect *ebpf.ProgramSpec `ebpf:"handle_connect"`
	HandleSendto  *ebpf.ProgramSpec `ebpf:"handle_sendto"`
	HandleSocket  *ebpf.ProgramSpec `ebpf:"handle_socket"`
}

// networkMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type networkMapSpecs struct {
	Rb *ebpf.MapSpec `ebpf:"rb"`
}

// networkVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type networkVariableSpecs struct {
	UnusedNetworkEvent *ebpf.VariableSpec `ebpf:"unused_network_event"`
}

// networkObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadNetworkObjects or ebpf.CollectionSpec.LoadAndAssign.
type networkObjects struct {
	networkPrograms
	networkMaps
	networkVariables
}

func (o *networkObjects) Close() error {
	return _NetworkClose(
		&o.networkPrograms,
		&o.networkMaps,
	)
}

// networkMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadNetworkObjects or ebpf.CollectionSpec.LoadAndAssign.
type networkMaps struct {
	Rb *ebpf.Map `ebpf:"rb"`
}

func (m *networkMaps) Close() error {
	return _NetworkClose(
		m.Rb,
	)
}

// networkVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadNetworkObjects or ebpf.CollectionSpec.LoadAndAssign.
type networkVariables struct {
	UnusedNetworkEvent *ebpf.Variable `ebpf:"unused_network_event"`
}

// networkPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadNetworkObjects or ebpf.CollectionSpec.LoadAndAssign.
type networkPrograms struct {
	HandleConnect *ebpf.Program `ebpf:"handle_connect"`
	HandleSendto  *ebpf.Program `ebpf:"handle_sendto"`
	HandleSocket  *ebpf.Program `ebpf:"handle_socket"`
}

func (p *networkPrograms) Close() error {
	return _NetworkClose(
		p.HandleConnect,
		p.HandleSendto,
		p.HandleSocket,
	)
}

func _NetworkClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed network_bpfel.o
var _NetworkBytes []byte
