// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package agent

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type rootkitRootkitEvent struct {
	_      structs.HostLayout
	Type   uint32
	Pid    uint32
	Ppid   uint32
	Uid    uint32
	Comm   [16]int8
	Arg1   int64
	Arg2   int64
	StrArg [64]int8
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	rootkitMapRb                 = "rb"
	rootkitProgHandleBpf         = "handle_bpf"
	rootkitProgHandleFinitModule = "handle_finit_module"
	rootkitProgHandleMemfdCreate = "handle_memfd_create"
	rootkitProgHandlePtrace      = "handle_ptrace"
	rootkitVarUnusedRootkitEvent = "unused_rootkit_event"
)

// loadRootkit returns the embedded CollectionSpec for rootkit.
func loadRootkit() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_RootkitBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load rootkit: %w", err)
	}

	return spec, err
}

// loadRootkitObjects loads rootkit and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*rootkitObjects
//	*rootkitPrograms
//	*rootkitMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadRootkitObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadRootkit()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// rootkitSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type rootkitSpecs struct {
	rootkitProgramSpecs
	rootkitMapSpecs
	rootkitVariableSpecs
}

// rootkitProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type rootkitProgramSpecs struct {
	HandleBpf         *ebpf.ProgramSpec `ebpf:"handle_bpf"`
	HandleFinitModule *ebpf.ProgramSpec `ebpf:"handle_finit_module"`
	HandleMemfdCreate *ebpf.ProgramSpec `ebpf:"handle_memfd_create"`
	HandlePtrace      *ebpf.ProgramSpec `ebpf:"handle_ptrace"`
}

// rootkitMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type rootkitMapSpecs struct {
	Rb *ebpf.MapSpec `ebpf:"rb"`
}

// rootkitVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type rootkitVariableSpecs struct {
	UnusedRootkitEvent *ebpf.VariableSpec `ebpf:"unused_rootkit_event"`
}

// rootkitObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadRootkitObjects or ebpf.CollectionSpec.LoadAndAssign.
type rootkitObjects struct {
	rootkitPrograms
	rootkitMaps
	rootkitVariables
}

func (o *rootkitObjects) Close() error {
	return _RootkitClose(
		&o.rootkitPrograms,
		&o.rootkitMaps,
	)
}

// rootkitMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadRootkitObjects or ebpf.CollectionSpec.LoadAndAssign.
type rootkitMaps struct {
	Rb *ebpf.Map `ebpf:"rb"`
}

func (m *rootkitMaps) Close() error {
	return _RootkitClose(
		m.Rb,
	)
}

// rootkitVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadRootkitObjects or ebpf.CollectionSpec.LoadAndAssign.
type rootkitVariables struct {
	UnusedRootkitEvent *ebpf.Variable `ebpf:"unused_rootkit_event"`
}

// rootkitPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadRootkitObjects or ebpf.CollectionSpec.LoadAndAssign.
type rootkitPrograms struct {
	HandleBpf         *ebpf.Program `ebpf:"handle_bpf"`
	HandleFinitModule *ebpf.Program `ebpf:"handle_finit_module"`
	HandleMemfdCreate *ebpf.Program `ebpf:"handle_memfd_create"`
	HandlePtrace      *ebpf.Program `ebpf:"handle_ptrace"`
}

func (p *rootkitPrograms) Close() error {
	return _RootkitClose(
		p.HandleBpf,
		p.HandleFinitModule,
		p.HandleMemfdCreate,
		p.HandlePtrace,
	)
}

func _RootkitClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed rootkit_bpfeb.o
var _RootkitBytes []byte
